# Generated by Django 5.2.6 on 2025-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=200),
        ),
    ]
